// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNxooS1ALnMhM75stx0jy79QWKL-SMRw',
    appId: '1:413134926267:android:25ec35a0919e074bd1149e',
    messagingSenderId: '413134926267',
    projectId: 'couplead-4ed67',
    storageBucket: 'couplead-4ed67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9Qzxdu6R_k1UykDQaKmL1vOO0XqP1dU',
    appId: '1:413134926267:ios:5d75dd7a801166ced1149e',
    messagingSenderId: '413134926267',
    projectId: 'couplead-4ed67',
    storageBucket: 'couplead-4ed67.firebasestorage.app',
    iosBundleId: 'com.example.coupleadFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT9Qzxdu6R_k1UykDQaKmL1vOO0XqP1dU',
    appId: '1:413134926267:ios:5d75dd7a801166ced1149e',
    messagingSenderId: '413134926267',
    projectId: 'couplead-4ed67',
    storageBucket: 'couplead-4ed67.firebasestorage.app',
    iosBundleId: 'com.example.coupleadFlutter',
  );
}
